### ISSUE TITLE
Binding Issue

### ISSUE THREAD

**Issue by szv** [CodebreakerApp/Codebreaker.Xaml#156]
@martinzikmund @morning4coffe-dev
As promised... Here is the issue we talked about today :)

https://github.com/CodebreakerApp/Codebreaker.Xaml/blob/2dad6dc23e2bf72c2fdbbaacb09c77ea89bffca5/src/Codebreaker.Uno/CodebreakerUno/Views/Components/PegSelectionComponent.xaml#L26

The above mentioned binding does not work on all platforms.
✅WinUI Head
❌WASM
❌Android
❌Skia/WPF
Not tested on other platforms

**Comment by Youssef1313** [comment]
Hi @szv 

It looks like this is relying on an Azure Container App that's currently off:

![image](https://github.com/CodebreakerApp/Codebreaker.Xaml/assets/31348972/88a9e50c-f458-4c0e-a133-89af839959d6)

So, can't get straight to reproducing this inside the app.

If you can get the app up and running again (or get a more simplified repro with a new unoapp), please let me know.

Thank you!

**Comment by Youssef1313** [comment]
Also, it could be that the binding is evaluated early at a point where the dictionary or game wasn't yet initialized. If you can try to manually call `Bindings.Update` in `GamePage` at a point when you know the dictionary is initialized and let us know if that works, it would help understanding the issue more.

**Comment by szv** [comment]
Hi @Youssef1313 

Yes we had some trouble with the backend. It's now redeployed (with a new Uri).
The backend should now be reachable, if you pull the latest changes.

Thanks

**Comment by Youssef1313** [comment]
@szv Thanks for the update.

I investigated this, and the root cause is https://github.com/unoplatform/uno/issues/9886.

Specifically, the problematic binding is this one:

https://github.com/CodebreakerApp/Codebreaker.Xaml/blob/b365dd20c604e7e6d645d376cdc7bc862e266373/src/Codebreaker.Uno/CodebreakerUno/Views/Pages/GamePage.xaml#L105-L109

The way this binding works on WinUI is that it calls `PegSelectionComponent.ViewModel` setter. However, in Uno, it calls `SetValue(ViewModelProperty, value)` directly, bypassing the following line:

https://github.com/CodebreakerApp/Codebreaker.Xaml/blob/b365dd20c604e7e6d645d376cdc7bc862e266373/src/Codebreaker.WinUI/Views/Components/PegSelectionComponent.xaml.cs#L22

As a workaround, the change in https://github.com/CodebreakerApp/Codebreaker.Xaml/pull/162 should work.
